import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebars for the documentation site.
 *
 * Both sidebars are autogenerated from the directories the sdd-content plugin
 * writes into docs-generated/. The _category_.json files the plugin emits into
 * each subdirectory control ordering and labels, so there is nothing to hand-
 * maintain here when an ADR or spec is added.
 */
const sidebars: SidebarsConfig = {
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  decisionsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'decisions',
    },
  ],
};

export default sidebars;
